version: "3.8"
services:
  influxdb:
    image: influxdb:2.7.1
    container_name: fantastigo-influxdb
    hostname: influxdb
    volumes:
      - fantastigo-influxdb2:/var/lib/influxdb2:rw
    ports:
      - '8086:8086'
    env_file:
      - tick/default.env
    networks: [ fantastigo ]

  chronograf:
    image: chronograf:1.9.4
    container_name: fantastigo-chronograf
    hostname: chronograf
    volumes:
      - fantastigo-chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    env_file:
      - tick/default.env
    networks: [ fantastigo ]
    depends_on:
      - influxdb

  fantastigo_pg:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - fantastigo_pg:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto
    container_name: fantastigo-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/log:/mosquitto/log/
      - mqtt-data:/mosquitto/data/
    networks: [ fantastigo ]

  mqtt-ui:
    image: smeagolworms4/mqtt-explorer
    container_name: fantastigo-mqtt-ui
    ports:
      - "4000:4000"
    networks: [ fantastigo ]

volumes:
  fantastigo-influxdb2:
  fantastigo_pg:
  fantastigo-chronograf:
  mqtt-data:

networks:
  fantastigo:
    name: fantastigo