env-name: dev
server:
  addr: :8080
  debug: true
  swagger-ui: true
  openapi-spec:
    - fleet.yaml
  timeout: 6e+10
db:
  host: "localhost"
  port: 5432
  user: "postgres-dev"
  password: "postgres-dev"
  dbname: "postgres-dev"