// Package ector provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package ector

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    string  `json:"code"`
	Message *string `json:"message,omitempty"`
}

// VehicleIdentityResponse defines model for VehicleIdentityResponse.
type VehicleIdentityResponse struct {
	Vin string `json:"vin"`
}

// VehicleMetricsResponse defines model for VehicleMetricsResponse.
type VehicleMetricsResponse map[string]interface{}

// VehicleStatusResponse defines model for VehicleStatusResponse.
type VehicleStatusResponse struct {
	Vin string `json:"vin"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// GetMetricsParams defines parameters for GetMetrics.
type GetMetricsParams struct {
	// MeasurementName filter metrics by given measurement name
	MeasurementName *string `form:"measurement-name,omitempty" json:"measurement-name,omitempty"`
}
